apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-academy-1-deployment 
  labels:
    app: backend-academy-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-academy-1
  template:
    metadata:
      labels:
        app: backend-academy-1
    spec:
      containers:
      - name: backend-academy-1
        image: credrope/backend-academy-1:latest
        ports:
        - containerPort: 3100
        env:
        - name: MONGODB_HOST
          value: mongo-courses-service
        readinessProbe:
          httpGet:
            path: /courses
            port: 3100
          initialDelaySeconds: 5
          periodSeconds: 2
---
apiVersion: v1
kind: Service
metadata:
  name: backend-academy-1-cluster-service
spec:
  type: ClusterIP
  selector:
    app: backend-academy-1
  ports:
    - protocol: TCP
      port: 3100
      targetPort: 3100

# Se usa para verificar que la api
---
apiVersion: v1
kind: Service
metadata:
  name: backend-academy-1-service 
spec:
  type: NodePort
  selector:
    app: backend-academy-1
  ports:
    - protocol: TCP
      port: 3100
      targetPort: 3100
      nodePort: 30100