apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-academy-2-deployment 
  labels:
    app: backend-academy-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-academy-2
  template:
    metadata:
      labels:
        app: backend-academy-2
    spec:
      containers:
      - name: backend-academy-2
        image: credrope/backend-academy-2:latest
        ports:
        - containerPort: 3200
        env:
        - name: MYSQL_HOST
          value: mysql-courses-service
        - name: MYSQL_USER
          value: root
        - name: MYSQL_PASSWORD
          value: password
        - name: MYSQL_DB
          value: udemy_db
        - name: PORT
          value: "3200"
        readinessProbe:
          httpGet:
            path: /courses
            port: 3200
          initialDelaySeconds: 5
          periodSeconds: 2
---
apiVersion: v1
kind: Service
metadata:
  name: backend-academy-2-cluster-service
spec:
  type: ClusterIP
  selector:
    app: backend-academy-2
  ports:
    - protocol: TCP
      port: 3200
      targetPort: 3200

# Se usa para verificar que la api
---
apiVersion: v1
kind: Service
metadata:
  name: backend-academy-2-service 
spec:
  type: NodePort
  selector:
    app: backend-academy-2
  ports:
    - protocol: TCP
      port: 3200
      targetPort: 3200
      nodePort: 30200