apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-academy-3-deployment 
  labels:
    app: backend-academy-3
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-academy-3
  template:
    metadata:
      labels:
        app: backend-academy-3
    spec:
      containers:
      - name: backend-academy-3
        image: credrope/backend-academy-3:latest
        ports:
        - containerPort: 3200
        env:
        - name: MARIADB_HOST
          value: maria-courses-service
        - name: MARIADB_USER
          value: root
        - name: MARIADB_PASSWORD
          value: password
        - name: MARIADB_DB
          value: courseradb
        - name: MARIADB_PORT
          value: "3306"
        - name: PORT
          value: "3300"
        readinessProbe:
          httpGet:
            path: /courses
            port: 3300
          initialDelaySeconds: 5
          periodSeconds: 2
---
apiVersion: v1
kind: Service
metadata:
  name: backend-academy-3-service 
spec:
  type: NodePort
  selector:
    app: backend-academy-3
  ports:
    - protocol: TCP
      port: 3300
      targetPort: 3300
      nodePort: 30300
---
apiVersion: v1
kind: Service
metadata:
  name: backend-academy-3-cluster-service
spec:
  type: ClusterIP
  selector:
    app: backend-academy-3
  ports:
    - protocol: TCP
      port: 3300
      targetPort: 3300