apiVersion: apps/v1
kind: Deployment
metadata:
  name: metasearch-deployment 
  labels:
    app: metasearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metasearch
  template:
    metadata:
      labels:
        app: metasearch
    spec:
      containers:
      - name: metasearch
        image: credrope/metasearch:latest
        ports:
        - containerPort: 5000
        env:
        - name: PLATZI_HOST
          value: backend-academy-1-cluster-service
        - name: UDEMY_HOST
          value: backend-academy-2-cluster-service
        - name: COURSERA_HOST
          value: backend-academy-3-cluster-service
        - name: PORT
          value: "5000"
---
apiVersion: v1
kind: Service
metadata:
  name: metasearch-service 
spec:
  type: NodePort
  selector:
    app: metasearch
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30900

# Servicio utilizado con Plataforma Cloud
# apiVersion: v1
# kind: Service
# metadata:
#   name: metasearch-service 
# spec:
#   type: LoadBalancer
#   selector:
#     app: metasearch
#   ports:
#     - protocol: TCP
#       port: 5000
#       targetPort: 5000